### ISSUE TITLE
[Question] Plugin does not work with Telegram from Microsoft Store

### ISSUE THREAD

**Issue by pleasehelpmewithtelegram** [SpriteOvO/Telegram-Anti-Revoke#45]
Hey

I tried to use your plugin and does not work.
My suggestion is that because I have telegram desktop app from Microsoft store and maybe that is not allowing run your plugin. windows 10.

Please tell me if I can do anything about it

**Comment by SpriteOvO** [comment]
Yes, the plugin doesn't work with Telegram from Microsoft Store, because the Microsoft Store applications are protected by Windows, and you can't even copy the plugin to Telegram root directory.

You can download and use Telegram [installation version](https://telegram.org/dl/desktop/win) or [portable version](https://telegram.org/dl/desktop/win_portable) that works well with the plugin.
