### ISSUE TITLE
Windows Defender detects the plugin as trojan virus

### ISSUE THREAD

**Issue by IronShell1207** [SpriteOvO/Telegram-Anti-Revoke#50]
### Describe the bug
Windows Anti malware service detects this file as trojan virus on windows 10

Here is the windows security's report
<a href="https://imgbb.com/"><img src="https://i.ibb.co/0VGxGxV/Clipboarder-2021-02-27.png" alt="Clipboarder-2021-02-27" border="0"></a>

### Configuration
* Operating system: Windows 10 20H2 19042.804
* Version of Telegram: 2.5.8

**Comment by SpriteOvO** [comment]
These links are the analysis results of the latest version of the plugin (currently v0.2.6) on VirusTotal:
[Win7](https://www.virustotal.com/gui/file/88e452f8f6eef6cf2a8dc64f97ae7185384b22a508600baaf7e2ec800b640fff/detection) [Win10](https://www.virustotal.com/gui/file/d0c53f6725e2ee4d89413a5f0c9f58764559bac99e865ddcac296ec82a7cb862/detection)

Since the plugin currently doesn‘t have a Microsoft software digital signature, its behavior may cause some anti-malware software to false positive.
I recommend that you add the plugin to the white-list of Windows defender or other anti-malware software to temporarily solve the problem.
This plugin is fully open source, if you really don't trust it, you can also check the source code and compile it yourself.

**Comment by w3bsme** [comment]
Same. Default settings. [OS Build 19042.844](https://support.microsoft.com/en-us/topic/february-24-2021-kb4601382-os-builds-19041-844-and-19042-844-preview-1a7ed2b4-017d-2644-a1e8-dd6bf14cba76)

**Comment by unkn000wn** [comment]
![Image 749](https://user-images.githubusercontent.com/83171705/115996145-c587bb00-a5e6-11eb-92f7-8587bcf2573e.jpg)

**Comment by cesarmau** [comment]
is false positive, because revoker need stay messages
