### ISSUE TITLE
64gram compatibility

### ISSUE THREAD

**Issue by Alispezzate** [SpriteOvO/Telegram-Anti-Revoke#87]
With the new versioning scheme of [64gram](https://github.com/TDesktop-x64/tdesktop) compatibility with the plugin is broken, I know third party clients are not supported but this is a very close fork of tdesktop, is there any chance you can fix it or at least give some indication to how to fix it? Thank you very much

**Comment by SpriteOvO** [comment]
Sorry for the late, I forgot this issue. The next plan for this project is to support Linux, so there may be no chance to support third-party clients.

In short, to fix it, you need to locate the plugin's code based on the error message, which is usually a binary bytes signature mismatch; or an offset change if there is no error message but it doesn't work.

The signature mismatch requires you to extract the contextual signature (it could be some logical jump, or upper level caller) from the old version that previously matched, that helps you locate the target location from the new version, and then update that signature. If the changes are very large and it is almost impossible to extract the contextual signature, you may need to compile the client yourself and get the `.pdb` file so that you can search for the target location directly in IDA, extract and update the signature.

Thxe offset changes requires you to calculate the new offsets of the members in the structure based on the commits in the client code, and you can check if these offsets are likely to be correct with the help of CE.

**Comment by Alispezzate** [comment]
I think I found the solution, as I said before, the problem started when the 64Gram developer changed the versioning scheme, restarting from v1.0.0. All I had to do was changing the lines in Source/Core/IRuntime.cpp about versioning and seems to be working for now. Altough it's a bit messy you can see the changes in my fork, what should I do now? Send a pull request or keep the fork separated?

**Comment by SpriteOvO** [comment]
@Alispezzate Cool! I think it's better to keep it separate, merging it might clutter the code a bit.
Just curious, what keeps you using 64gram? The official client now has 64-bit support.

**Comment by Alispezzate** [comment]
The main reason I use 64Gram is the possibility  to use more than 3 accounts, but there are plenty of useful features that you can find [here](https://github.com/TDesktop-x64/tdesktop/blob/dev/features.md)

**Comment by Alispezzate** [comment]
For anyone interested I pubblished the fixed release in my [fork](https://github.com/Alispezzate/64Gram-Anti-Revoke/releases/tag/0.4.2.1), therefore I close the issue. Thank you very much @SpriteOvO
